// provinces.js
export const provinces = [
  { id: 1, value: 'hanoi', label: 'Hà Nội' },
  { id: 2, value: 'hochiminh', label: 'TP. Hồ Chí Minh' },
  { id: 3, value: 'haiphong', label: 'Hải Phòng' },
  { id: 4, value: 'cantho', label: 'Cần Thơ' },
  { id: 5, value: 'danang', label: 'Đà Nẵng' },
  { id: 6, value: 'angiang', label: 'An Giang' },
  { id: 7, value: 'bacgiang', label: 'Bắc Giang' },
  { id: 8, value: 'backan', label: 'Bắc Kạn' },
  { id: 9, value: 'baclieu', label: 'Bạc Liêu' },
  { id: 10, value: 'bacninh', label: 'Bắc Ninh' },
  { id: 11, value: 'baria-vungtau', label: 'Bà Rịa - Vũng Tàu' },
  { id: 12, value: 'ben-tre', label: 'Bến Tre' },
  { id: 13, value: 'binhduong', label: 'Bình Dương' },
  { id: 14, value: 'binhdinh', label: 'Bình Định' },
  { id: 15, value: 'binhphuoc', label: 'Bình Phước' },
  { id: 16, value: 'binhthuan', label: 'Bình Thuận' },
  { id: 17, value: 'camau', label: 'Cà Mau' },
  { id: 18, value: 'caobang', label: 'Cao Bằng' },
  { id: 19, value: 'daklak', label: 'Đắk Lắk' },
  { id: 20, value: 'daknong', label: 'Đắk Nông' },
  { id: 21, value: 'dienbien', label: 'Điện Biên' },
  { id: 22, value: 'dongnai', label: 'Đồng Nai' },
  { id: 23, value: 'dongthap', label: 'Đồng Tháp' },
  { id: 24, value: 'gialai', label: 'Gia Lai' },
  { id: 25, value: 'hagiang', label: 'Hà Giang' },
  { id: 26, value: 'hanam', label: 'Hà Nam' },
  { id: 27, value: 'hatinh', label: 'Hà Tĩnh' },
  { id: 28, value: 'haiduong', label: 'Hải Dương' },
  { id: 29, value: 'haugiang', label: 'Hậu Giang' },
  { id: 30, value: 'hoabinh', label: 'Hòa Bình' },
  { id: 31, value: 'hungyen', label: 'Hưng Yên' },
  { id: 32, value: 'khanhhoa', label: 'Khánh Hòa' },
  { id: 33, value: 'kiengiang', label: 'Kiên Giang' },
  { id: 34, value: 'kontum', label: 'Kon Tum' },
  { id: 35, value: 'laichau', label: 'Lai Châu' },
  { id: 36, value: 'lamdong', label: 'Lâm Đồng' },
  { id: 37, value: 'langson', label: 'Lạng Sơn' },
  { id: 38, value: 'laocai', label: 'Lào Cai' },
  { id: 39, value: 'longan', label: 'Long An' },
  { id: 40, value: 'namdinh', label: 'Nam Định' },
  { id: 41, value: 'nghean', label: 'Nghệ An' },
  { id: 42, value: 'ninhbinh', label: 'Ninh Bình' },
  { id: 43, value: 'ninhthuan', label: 'Ninh Thuận' },
  { id: 44, value: 'phutho', label: 'Phú Thọ' },
  { id: 45, value: 'phuyen', label: 'Phú Yên' },
  { id: 46, value: 'quangbinh', label: 'Quảng Bình' },
  { id: 47, value: 'quangnam', label: 'Quảng Nam' },
  { id: 48, value: 'quangngai', label: 'Quảng Ngãi' },
  { id: 49, value: 'quangninh', label: 'Quảng Ninh' },
  { id: 50, value: 'quangtri', label: 'Quảng Trị' },
  { id: 51, value: 'soctrang', label: 'Sóc Trăng' },
  { id: 52, value: 'sonla', label: 'Sơn La' },
  { id: 53, value: 'tayninh', label: 'Tây Ninh' },
  { id: 54, value: 'thaibinh', label: 'Thái Bình' },
  { id: 55, value: 'thainguyen', label: 'Thái Nguyên' },
  { id: 56, value: 'thanhhoa', label: 'Thanh Hóa' },
  { id: 57, value: 'thuathienhue', label: 'Thừa Thiên Huế' },
  { id: 58, value: 'tiengiang', label: 'Tiền Giang' },
  { id: 59, value: 'travinh', label: 'Trà Vinh' },
  { id: 60, value: 'tuyenquang', label: 'Tuyên Quang' },
  { id: 61, value: 'vinhlong', label: 'Vĩnh Long' },
  { id: 62, value: 'vinhphuc', label: 'Vĩnh Phúc' },
  { id: 63, value: 'yenbai', label: 'Yên Bái' }
];
